FROM golang:1.21.6-alpine AS builder

WORKDIR /app
COPY . ./

RUN CGO_ENABLED=0 go build -v -ldflags "-s -w -X main.programVersion=latest"

FROM registry.access.redhat.com/ubi8-micro AS multi-stage

COPY --from=builder /app/pg_tileserv /app/
COPY --from=builder /app/assets /app/assets

VOLUME ["/config"]

USER 1001
EXPOSE 7800

WORKDIR /app
ENTRYPOINT ["/app/pg_tileserv"]
CMD []
